name = "hello-function"
api_version = "2026-07"

[build]
command = "cargo build --target wasm32-unknown-unknown --release --locked"
path = "target/wasm32-unknown-unknown/release/hello_function.wasm"

[[extensions.targeting]]
target = "purchase.product-discount.run"
input_query = "src/input.graphql"
export = "run"

[extensions.ui]
paths = { create = "/app/discounts/:functionId/new", details = "/app/discounts/:functionId/:id" }
