/**
 * File: routes/app.order.tsx
 * Author: yuntongsoft
 * Date: 2026/09/19
 * Purpose: Auto-generated CRUD page for Order model
 * Generated by: npm run generate Order
 *
 * Customize this page to match your business needs:
 *   - Adjust form fields and validation
 *   - Add business logic in the action
 *   - Modify table columns and display
 *
 * Dependencies: prisma, shopify-auth, csrf, i18n, rate-limiter
 */
import { json } from "@remix-run/node";
import type { ActionFunctionArgs, LoaderFunctionArgs } from "@remix-run/node";
import { apiError, apiSuccess } from "~/utils/api-response";
import { shopifyAdmin } from "~/services/shopify-admin";
import { useLoaderData, useSubmit, useRouteLoaderData, useNavigation } from "@remix-run/react";
import {
  Page,
  Card,
  IndexTable,
  Button,
  Modal,
  FormLayout,
  TextField,
  Select,
  Text,
  Badge,
  Icon,
  BlockStack,
} from "@shopify/polaris";
import { EditIcon, DeleteIcon, PlusIcon, RefreshIcon } from "@shopify/polaris-icons";
import { useState, useCallback } from "react";
import prisma from "~/db.server";
import { authenticatePage, authResponse } from "~/utils/shopify-auth.server";
import { generateCsrfToken, validateCsrfRequest } from "~/utils/csrf";
import { rateLimit, RATE_LIMIT_PRESETS } from "~/utils/rate-limiter";
import { createLogger } from "~/utils/logger";
import { useTranslation, getTranslation } from "~/utils/i18n";

export { PageErrorBoundary as ErrorBoundary } from "~/components/PageErrorBoundary";

const logger = createLogger({ module: "order" });

// ─────────────────────────────────────────────────────────────────────────────
// LOADER — Fetch orders for the current shop (cursor-based pagination)
// ─────────────────────────────────────────────────────────────────────────────
export const loader = async ({ request }: LoaderFunctionArgs) => {
  const auth = await authenticatePage(request);
  if (!auth.ok) return authResponse(auth);
  const shop = auth.shop;

  const url = new URL(request.url);
  const cursorParam = url.searchParams.get("cursor");
  const PAGE_SIZE = 50;

  // SECURITY: Validate cursor format — must be a valid Prisma CUID (alphanumeric)
  if (cursorParam && !/^[a-zA-Z0-9]+$/.test(cursorParam)) {
    return apiError("Invalid cursor parameter", 400);
  }

  const orders = await prisma.order.findMany({
    where: { shopId: shop.id },
    orderBy: { createdAt: "desc" },
    take: PAGE_SIZE + 1,
    ...(cursorParam ? { cursor: { id: cursorParam }, skip: 1 } : {}),
  });

  // Determine if there are more results
  const hasMore = orders.length > PAGE_SIZE;
  const items = hasMore ? orders.slice(0, PAGE_SIZE) : orders;
  const nextCursor = hasMore ? items[items.length - 1].id : null;

  return json({ orders, nextCursor, shopPlan: shop.plan, csrfToken: generateCsrfToken() });
};

// ─────────────────────────────────────────────────────────────────────────────
// ACTION — Handle create / update / delete / sync
// ─────────────────────────────────────────────────────────────────────────────
export const action = async ({ request }: ActionFunctionArgs) => {
  const auth = await authenticatePage(request);
  if (!auth.ok) return authResponse(auth);
  const shop = auth.shop;

  // Rate limiting
  const ip = request.headers.get("x-forwarded-for") || "unknown";
  const blocked = await rateLimit(`order:${shop.id}:${ip}`, RATE_LIMIT_PRESETS.write);
  if (blocked) {
    return apiError(
      `Too many requests. Retry in ${blocked.retryAfter}s`,
      429,
      undefined,
      { "Retry-After": String(Math.ceil(blocked.retryAfter / 1000)) }
    );
  }

  // CSRF validation
  let formData: FormData;
  try {
    formData = await validateCsrfRequest(request);
  } catch {
    return apiError("Invalid or expired CSRF token. Please refresh the page.", 403);
  }
  const intent = formData.get("intent") as string;

  // ── Sync from Shopify ──────────────────────────────────────────────────
  if (intent === "sync") {
    try {
      const api = shopifyAdmin(shop.shopifyDomain);
      const result = await api.getOrders({ first: 100 });

      await prisma.$transaction(
        result.items.map((order) =>
          prisma.order.upsert({
            where: { id: order.id },
            update: {
              orderNumber: order.name,
              customer: order.email || "",
              amount: parseFloat(order.totalPrice),
              status: `${order.financialStatus}/${order.fulfillmentStatus}`,
            },
            create: {
              id: order.id,
              shopId: shop.id,
              orderNumber: order.name,
              customer: order.email || "",
              amount: parseFloat(order.totalPrice),
              status: `${order.financialStatus}/${order.fulfillmentStatus}`,
            },
          })
        )
      );

      logger.info({ shopId: shop.id, synced: result.items.length }, "Orders synced from Shopify");
      const { t: st } = getTranslation(shop.locale || "en");
      return apiSuccess(undefined, st("orders.syncSuccess", { count: result.items.length }));
    } catch (err) {
      logger.error({ shopId: shop.id, error: err instanceof Error ? err.message : String(err) }, "Shopify sync failed");
      return apiError("Failed to sync orders from Shopify. Please try again.", 500);
    }
  }

  switch (intent) {
    case "create": {
      const orderNumberCreate = String(formData.get("orderNumber") || "");
      if (!orderNumberCreate || orderNumberCreate.length > 500) {
        return apiError("Order Number is required and must be under 500 characters", 400);
      }
      const customerCreate = String(formData.get("customer") || "");
      if (!customerCreate || customerCreate.length > 500) {
        return apiError("Customer is required and must be under 500 characters", 400);
      }
      const amountCreate = Number(formData.get("amount") || 0);
      if (isNaN(amountCreate) || amountCreate < 0 || amountCreate > 99_999_999) {
        return apiError("Amount must be a number between 0 and 99,999,999", 400);
      }
      const statusCreate = String(formData.get("status") || "");
      if (!statusCreate || statusCreate.length > 255) {
        return apiError("Status is required and must be under 255 characters", 400);
      }
      const item = await prisma.order.create({
        data: {
          shopId: shop.id,
          orderNumber: orderNumberCreate,
          customer: customerCreate,
          amount: amountCreate,
          status: statusCreate,
          note: String(formData.get("note") || ""),
        },
      });
      logger.info({ shopId: shop.id, id: item.id }, "Order created");
      return apiSuccess({ item });
    }

    case "update": {
      const id = String(formData.get("id"));
      const existing = await prisma.order.findFirst({ where: { id, shopId: shop.id } });
      if (!existing) return apiError("Not found", 404);

      const orderNumberUpdate = String(formData.get("orderNumber") || "");
      if (!orderNumberUpdate || orderNumberUpdate.length > 500) {
        return apiError("Order Number is required and must be under 500 characters", 400);
      }
      const customerUpdate = String(formData.get("customer") || "");
      if (!customerUpdate || customerUpdate.length > 500) {
        return apiError("Customer is required and must be under 500 characters", 400);
      }
      const amountUpdate = Number(formData.get("amount") || 0);
      if (isNaN(amountUpdate) || amountUpdate < 0 || amountUpdate > 99_999_999) {
        return apiError("Amount must be a number between 0 and 99,999,999", 400);
      }
      const statusUpdate = String(formData.get("status") || "");
      if (!statusUpdate || statusUpdate.length > 255) {
        return apiError("Status is required and must be under 255 characters", 400);
      }
      const data: Record<string, unknown> = {};
      data.orderNumber = orderNumberUpdate;
      data.customer = customerUpdate;
      data.amount = amountUpdate;
      data.status = statusUpdate;
      data.note = String(formData.get("note") || "");

      const updated = await prisma.order.update({ where: { id }, data });
      logger.info({ shopId: shop.id, id: updated.id }, "Order updated");
      return apiSuccess({ item: updated });
    }

    case "delete": {
      const id = String(formData.get("id"));
      const existing = await prisma.order.findFirst({ where: { id, shopId: shop.id } });
      if (!existing) return apiError("Not found", 404);

      await prisma.order.delete({ where: { id } });
      logger.info({ shopId: shop.id, id }, "Order deleted");
      return apiSuccess();
    }

    default:
      return apiError("Unknown intent", 400);
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// UI
// ─────────────────────────────────────────────────────────────────────────────
interface OrderItem {
  id: string;
  orderNumber: string;
  customer: string;
  amount: number;
  status: string;
  note: string;
}

interface OrderLoaderData {
  orders: OrderItem[];
  nextCursor: string | null;
  shopPlan: string;
  csrfToken: string;
}

// Status format: "financialStatus/fulfillmentStatus" (e.g., "PAID/UNFULFILLED")
function statusTone(status: string): "success" | "warning" | "critical" | "info" | "attention" {
  const [financial, fulfillment] = status.toLowerCase().split("/");
  switch (financial) {
    case "paid": return fulfillment === "fulfilled" ? "success" : "info";
    case "authorized":
    case "partially_paid": return "attention";
    case "pending": return "warning";
    case "partially_refunded": return "warning";
    case "refunded":
    case "voided":
    case "expired": return "critical";
    case "cancelled": return "critical";
    default: return "info";
  }
}

export default function OrderPage() {
  const { orders = [], nextCursor = null, csrfToken = "" } = useLoaderData<OrderLoaderData>();
  const submit = useSubmit();
  const { t } = useTranslation(
    useRouteLoaderData<typeof import("~/routes/app").loader>("routes/app")?.locale
  );

  const [modalOpen, setModalOpen] = useState(false);
  const [deleteModalOpen, setDeleteModalOpen] = useState(false);
  const [deleteTargetId, setDeleteTargetId] = useState<string | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [orderNumber, setOrderNumber] = useState("");
  const [customer, setCustomer] = useState("");
  const [amount, setAmount] = useState(0);
  const [status, setStatus] = useState("pending");
  const [note, setNote] = useState("");

  const handleNew = useCallback(() => {
    setEditingId(null);
    setError(null);
    setOrderNumber("");
    setCustomer("");
    setAmount(0);
    setStatus("pending");
    setNote("");
    setModalOpen(true);
  }, []);

  const handleEdit = useCallback((item: OrderItem) => {
    setEditingId(item.id);
    setError(null);
    setOrderNumber(item.orderNumber ?? "");
    setCustomer(item.customer ?? "");
    setAmount(item.amount ?? 0);
    setStatus(item.status ?? "");
    setNote(item.note ?? "");
    setModalOpen(true);
  }, []);

  const navigation = useNavigation();
  const isSubmitting = navigation.state === "submitting";

  const handleSave = useCallback(() => {
    setError(null);
    const intent = editingId ? "update" : "create";
    const data: Record<string, string> = { intent, csrfToken };
    if (editingId) data.id = editingId;
    data["orderNumber"] = String(orderNumber);
    data["customer"] = String(customer);
    data["amount"] = String(amount);
    data["status"] = String(status);
    data["note"] = String(note);
    submit(data, { method: "post" });
    setModalOpen(false);
  }, [editingId, orderNumber, customer, amount, status, note, csrfToken, submit]);

  const handleSync = useCallback(() => {
    submit({ intent: "sync", csrfToken }, { method: "post" });
  }, [csrfToken, submit]);

  const handleDeleteRequest = useCallback((id: string) => {
    setDeleteTargetId(id);
    setDeleteModalOpen(true);
  }, []);

  const handleDeleteConfirm = useCallback(() => {
    if (deleteTargetId) {
      submit({ intent: "delete", id: deleteTargetId, csrfToken }, { method: "post" });
    }
    setDeleteModalOpen(false);
    setDeleteTargetId(null);
  }, [deleteTargetId, csrfToken, submit]);

  return (
    <Page
      title={t("orders.title")}
      primaryAction={{
        content: t("orders.newOrder"),
        icon: PlusIcon,
        onAction: handleNew,
      }}
      secondaryActions={[
        {
          content: t("orders.syncFromShopify"),
          icon: RefreshIcon,
          onAction: handleSync,
          loading: isSubmitting,
        },
      ]}
    >
      <BlockStack gap="400">
        {error && (
          <Card>
            <Text as="p" tone="critical">{error}</Text>
          </Card>
        )}
        <Card>
          {orders.length === 0 ? (
            <div className="sf-empty-state">
              <img src="/images/empty-state.png" alt="" className="sf-empty-state-image" />
              <Text as="h2" variant="headingMd">{t("orders.noOrders")}</Text>
              <Text as="p" variant="bodyMd" tone="subdued">{t("orders.noOrdersHint")}</Text>
              <div style={{ marginTop: 16 }}>
                <Button variant="primary" icon={PlusIcon} onClick={handleNew}>
                  {t("orders.createOrder")}
                </Button>
              </div>
            </div>
          ) : (
            <IndexTable
              resourceName={{ singular: t("orders.resourceSingular"), plural: t("orders.resourcePlural") }}
              itemCount={orders.length}
              headings={[
              { title: t("orders.orderNumber") },
              { title: t("orders.customer") },
              { title: t("orders.amount") },
              { title: t("orders.status") },
              { title: t("orders.actions") },
              ]}
              selectable={false}
            >
              {orders.map((item: OrderItem, index: number) => (
                <IndexTable.Row id={item.id} key={item.id} position={index}>
                  <IndexTable.Cell>
                  <Text as="span" variant="bodyMd">{String(item.orderNumber ?? "—")}</Text>
                </IndexTable.Cell>
                <IndexTable.Cell>
                  <Text as="span" variant="bodyMd">{String(item.customer ?? "—")}</Text>
                </IndexTable.Cell>
                <IndexTable.Cell>
                  <Text as="span" variant="bodyMd">{String(item.amount ?? "—")}</Text>
                </IndexTable.Cell>
                <IndexTable.Cell>
                  {(() => {
                    const [financial, fulfillment] = (item.status || "").split("/");
                    return (
                      <>
                        {financial && <Badge tone={statusTone(item.status)}>{t(`orders.statusOptions.${financial.toLowerCase()}`)}</Badge>}
                        {fulfillment && <Badge tone="info">{t(`orders.statusOptions.${fulfillment.toLowerCase()}`)}</Badge>}
                      </>
                    );
                  })()}
                </IndexTable.Cell>
                  <IndexTable.Cell>
                    <div style={{ display: "flex", gap: "4px" }}>
                      <Button
                        variant="plain"
                        icon={EditIcon}
                        onClick={() => handleEdit(item as OrderItem)}
                        aria-label={t("orders.edit")}
                      />
                      <Button
                        variant="plain"
                        tone="critical"
                        icon={DeleteIcon}
                        onClick={() => handleDeleteRequest(item.id)}
                        aria-label={t("orders.delete")}
                      />
                    </div>
                  </IndexTable.Cell>
                </IndexTable.Row>
              ))}
            </IndexTable>
          )}
          {nextCursor && (
            <div style={{ padding: "16px", textAlign: "center" }}>
              <Button variant="plain" url={`?cursor=${nextCursor}`}>
                {t("orders.loadMore")}
              </Button>
            </div>
          )}
        </Card>

        {/* Create / Edit Modal */}
        <Modal
          open={modalOpen}
          onClose={() => setModalOpen(false)}
          title={editingId ? t("orders.editOrder") : t("orders.createOrder")}
          primaryAction={{
            content: t("orders.save"),
            onAction: handleSave,
            loading: isSubmitting,
          }}
          secondaryActions={[{ content: t("orders.cancel"), onAction: () => setModalOpen(false) }]}
        >
          <Modal.Section>
            <FormLayout>
              <TextField
              label={t("orders.orderNumber")}
              value={orderNumber}
              onChange={setOrderNumber}
              autoComplete="off"
            />
            <TextField
              label={t("orders.customer")}
              value={customer}
              onChange={setCustomer}
              autoComplete="off"
            />
            <TextField
              label={t("orders.amount")}
              type="number"
              value={String(amount)}
              onChange={(val) => setAmount(Number(val))}
              autoComplete="off"
            />
            <Select
              label={t("orders.status")}
              options={[
                // TODO: Customize these options based on your business logic
                { label: t("orders.statusOptions.pending"), value: "pending" },
                { label: t("orders.statusOptions.paid"), value: "paid" },
                { label: t("orders.statusOptions.cancelled"), value: "cancelled" },
              ]}
              value={status}
              onChange={setStatus}
            />
            <TextField
              label={t("orders.note")}
              value={note}
              onChange={setNote}
              multiline={3}
              autoComplete="off"
            />
            </FormLayout>
          </Modal.Section>
        </Modal>

        {/* Delete Confirmation Modal */}
        <Modal
          open={deleteModalOpen}
          onClose={() => setDeleteModalOpen(false)}
          title={t("orders.deleteConfirmTitle")}
          primaryAction={{
            content: t("orders.deleteConfirmAction"),
            destructive: true,
            onAction: handleDeleteConfirm,
          }}
          secondaryActions={[{ content: t("orders.cancel"), onAction: () => setDeleteModalOpen(false) }]}
        >
          <Modal.Section>
            <Text as="p">{t("orders.deleteConfirmMessage")}</Text>
          </Modal.Section>
        </Modal>
      </BlockStack>
    </Page>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// i18n keys — Ensure these exist in your locale files (en.json, zh.json, etc.)
//
// orders: {
//   title, newOrder, noOrders, noOrdersHint, createOrder, editOrder,
//   orderNumber, customer, amount, status, note, actions,
//   edit, delete, save, cancel, loadMore,
//   resourceSingular, resourcePlural,
//   deleteConfirmTitle, deleteConfirmMessage, deleteConfirmAction,
//   statusOptions: { pending, processing, delivered, ... }
// }
// ─────────────────────────────────────────────────────────────────────────────
