/**
 * File: demo/routes/order.tsx
 * Author: yuntongsoft
 * Date: 2026/09/09
 * Purpose: [DEMO] Auto-generated CRUD page for Order model
 * Generated by: npm run generate Order
 *
 * ============================================================================
 * DEMO COMPONENT — Pure React UI, no server-only imports
 * Server logic (loader/action) lives in routes/app.order.tsx
 * ============================================================================
 *
 * Dependencies: @shopify/polaris, @remix-run/react, i18n
 */
import { useLoaderData, useSubmit, useRouteLoaderData } from "@remix-run/react";
import {
  Page,
  Card,
  IndexTable,
  Button,
  Modal,
  FormLayout,
  TextField,
  Select,
  Text,
  Badge,
  Icon,
  BlockStack,
} from "@shopify/polaris";
import { EditIcon, DeleteIcon, PlusIcon, OrderIcon } from "@shopify/polaris-icons";
import { useState, useCallback } from "react";
import { useTranslation } from "~/utils/i18n";

// ─────────────────────────────────────────────────────────────────────────────
// Types (must match wrapper loader response shape)
// ─────────────────────────────────────────────────────────────────────────────
interface OrderItem {
  id: string;
  orderNumber: string;
  customer: string;
  amount: number;
  status: string;
  note: string;
}

interface OrderLoaderData {
  orders: OrderItem[];
  nextCursor: string | null;
  shopPlan: string;
  csrfToken: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Status → Badge tone mapping
// Status format: "financialStatus/fulfillmentStatus" (e.g., "paid/unfulfilled")
// ─────────────────────────────────────────────────────────────────────────────
function statusTone(status: string): "success" | "warning" | "critical" | "info" | "attention" {
  const [financial, fulfillment] = status.split("/");
  // Financial status takes priority for color
  switch (financial) {
    case "paid": return fulfillment === "fulfilled" ? "success" : "info";
    case "pending": return "warning";
    case "refunded": return "critical";
    case "refunding": return "attention";
    case "cancelled": return "critical";
    default: return "info";
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// UI
// ─────────────────────────────────────────────────────────────────────────────
export default function OrderPage() {
  const { orders = [], nextCursor = null, csrfToken = "" } = useLoaderData<OrderLoaderData>();
  const submit = useSubmit();
  const { t } = useTranslation(useRouteLoaderData<typeof import("~/routes/app").loader>("routes/app")?.locale);

  const [modalOpen, setModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [orderNumber, setOrderNumber] = useState("");
  const [customer, setCustomer] = useState("");
  const [amount, setAmount] = useState(0);
  const [status, setStatus] = useState("pending");
  const [note, setNote] = useState("");

  const handleNew = useCallback(() => {
    setEditingId(null);
    setOrderNumber("");
    setCustomer("");
    setAmount(0);
    setStatus("pending");
    setNote("");
    setModalOpen(true);
  }, []);

  const handleEdit = useCallback((item: OrderItem) => {
    setEditingId(item.id);
    setOrderNumber(item.orderNumber ?? "");
    setCustomer(item.customer ?? "");
    setAmount(item.amount ?? 0);
    setStatus(item.status ?? "");
    setNote(item.note ?? "");
    setModalOpen(true);
  }, []);

  const handleSave = useCallback(() => {
    const intent = editingId ? "update" : "create";
    const data: Record<string, string> = { intent, csrfToken };
    if (editingId) data.id = editingId;
    data["orderNumber"] = String(orderNumber);
    data["customer"] = String(customer);
    data["amount"] = String(amount);
    data["status"] = String(status);
    data["note"] = String(note);
    submit(data, { method: "post" });
    setModalOpen(false);
  }, [editingId, orderNumber, customer, amount, status, note, csrfToken, submit]);

  const handleDelete = useCallback(
    (id: string) => submit({ intent: "delete", id, csrfToken }, { method: "post" }),
    [submit, csrfToken]
  );

  return (
    <Page
      title={t("orders.title")}
      subtitle={t("orders.subtitle")}
      primaryAction={{
        content: t("orders.newOrder"),
        icon: PlusIcon,
        onAction: handleNew,
      }}
    >
      <BlockStack gap="400">
        <Card>
          {orders.length === 0 ? (
            <div className="sf-empty-state">
              <div className="sf-empty-state-icon">
                <Icon source={OrderIcon} tone="base" />
              </div>
              <Text as="h2" variant="headingMd">{t("orders.noOrders")}</Text>
              <Text as="p" variant="bodyMd" tone="subdued" >{t("orders.noOrdersHint")}</Text>
              <div style={{ marginTop: 16 }}>
                <Button variant="primary" icon={PlusIcon} onClick={handleNew}>
                  {t("orders.createOrder")}
                </Button>
              </div>
            </div>
          ) : (
            <IndexTable
              resourceName={{ singular: "order", plural: "orders" }}
              itemCount={orders.length}
              headings={[
                { title: t("orders.orderNumber") },
                { title: t("orders.customer") },
                { title: t("orders.amount") },
                { title: t("orders.status") },
                { title: t("orders.actions") },
              ]}
              selectable={false}
            >
              {orders.map((item: OrderItem, index: number) => (
                <IndexTable.Row id={item.id} key={item.id} position={index}>
                  <IndexTable.Cell>
                    <Text as="span" variant="bodyMd" fontWeight="bold">
                      {String(item.orderNumber ?? "—")}
                    </Text>
                  </IndexTable.Cell>
                  <IndexTable.Cell>
                    <Text as="span" variant="bodyMd">{String(item.customer ?? "—")}</Text>
                  </IndexTable.Cell>
                  <IndexTable.Cell>
                    <Text as="span" variant="bodyMd">{String(item.amount ?? "—")}</Text>
                  </IndexTable.Cell>
                  <IndexTable.Cell>
                    {(() => {
                      const [financial, fulfillment] = (item.status || "").split("/");
                      return (
                        <>
                          {financial && <Badge tone={statusTone(item.status)}>{t(`orders.statusOptions.${financial}`)}</Badge>}
                          {fulfillment && <Badge tone="info">{t(`orders.statusOptions.${fulfillment}`)}</Badge>}
                        </>
                      );
                    })()}
                  </IndexTable.Cell>
                  <IndexTable.Cell>
                    <div className="sf-table-actions">
                      <Button
                        variant="plain"
                        icon={EditIcon}
                        onClick={() => handleEdit(item as OrderItem)}
                        aria-label={t("orders.edit")}
                      />
                      <Button
                        variant="plain"
                        tone="critical"
                        icon={DeleteIcon}
                        onClick={() => handleDelete(item.id)}
                        aria-label={t("orders.delete")}
                      />
                    </div>
                  </IndexTable.Cell>
                </IndexTable.Row>
              ))}
            </IndexTable>
          )}
          {nextCursor && (
            <div style={{ padding: "16px", textAlign: "center" }}>
              <Button variant="plain" url={`?cursor=${nextCursor}`}>
                {t("orders.loadMore")}
              </Button>
            </div>
          )}
        </Card>

        <Modal
          open={modalOpen}
          onClose={() => setModalOpen(false)}
          title={editingId ? t("orders.editOrder") : t("orders.createOrder")}
          primaryAction={{ content: t("orders.save"), onAction: handleSave }}
          secondaryActions={[{ content: t("orders.cancel"), onAction: () => setModalOpen(false) }]}
        >
          <Modal.Section>
            <FormLayout>
              <TextField
                label={t("orders.orderNumber")}
                value={orderNumber}
                onChange={setOrderNumber}
                autoComplete="off"
              />
              <TextField
                label={t("orders.customer")}
                value={customer}
                onChange={setCustomer}
                autoComplete="off"
              />
              <TextField
                label={t("orders.amount")}
                type="number"
                value={String(amount)}
                onChange={(val) => setAmount(Number(val))}
                autoComplete="off"
              />
              <Select
                label={t("orders.status")}
                options={[
                  { label: t("orders.statusOptions.pending"), value: "pending" },
                  { label: t("orders.statusOptions.processing"), value: "processing" },
                  { label: t("orders.statusOptions.shipped"), value: "shipped" },
                  { label: t("orders.statusOptions.delivered"), value: "delivered" },
                  { label: t("orders.statusOptions.cancelled"), value: "cancelled" },
                  { label: t("orders.statusOptions.refunded"), value: "refunded" },
                ]}
                value={status}
                onChange={setStatus}
              />
              <TextField
                label={t("orders.note")}
                value={note}
                onChange={setNote}
                multiline={3}
                autoComplete="off"
              />
            </FormLayout>
          </Modal.Section>
        </Modal>
      </BlockStack>
    </Page>
  );
}
