/**
 * File: scripts/setup.ts
 * Purpose: Unified one-stop setup for ShopForge.
 *
 * What it does:
 *   1. Database — select provider (default: SQLite), generate .env with secrets
 *   2. Shopify  — guide user to create app, collect credentials interactively
 *   3. Database  — auto-run `prisma db push` to create tables
 *
 * Usage:
 *   npm run setup                    # Full interactive setup
 *   npm run setup -- --quick         # SQLite + skip Shopify (fill credentials later)
 *   npm run setup -- --provider pg   # Non-interactive: configure PostgreSQL
 *   npm run setup -- --db-only       # Only configure database
 */
import { spawnSync } from "child_process";
import fs from "fs";
import path from "path";
import crypto from "crypto";
import readline from "readline";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const ENV_PATH = path.join(ROOT, ".env");
const SCHEMA_PATH = path.join(ROOT, "prisma", "schema.prisma");
const SHOPIFY_TOML = path.join(ROOT, "shopify.app.toml");

// ─── Database presets ────────────────────────────────────────────────────────

const PRESETS: Record<string, { label: string; url: string }> = {
  sqlite: {
    label: "SQLite (zero config, recommended for development)",
    url: "file:./dev.db",
  },
  postgresql: {
    label: "PostgreSQL (recommended for production)",
    url: "postgresql://user:password@localhost:5432/shopforge",
  },
  mysql: {
    label: "MySQL",
    url: "mysql://user:password@localhost:3306/shopforge",
  },
};

// ─── Terminal helpers ────────────────────────────────────────────────────────

const C = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  cyan: "\x1b[36m",
  red: "\x1b[31m",
  dim: "\x1b[90m",
};

function log(msg: string) {
  console.log(`${C.cyan}  ●${C.reset} ${msg}`);
}

function ok(msg: string) {
  console.log(`  ${C.green}✓${C.reset} ${msg}`);
}

function warn(msg: string) {
  console.log(`  ${C.yellow}!${C.reset} ${msg}`);
}

function fail(msg: string): never {
  console.error(`  ${C.red}✗${C.reset} ${msg}`);
  process.exit(1);
}

function banner(text: string) {
  console.log(`\n  ${C.bold}━━━ ${text} ━━━${C.reset}\n`);
}

// ─── Interactive prompts ─────────────────────────────────────────────────────

function createRL() {
  return readline.createInterface({ input: process.stdin, output: process.stdout });
}

function ask(question: string, defaultValue?: string): Promise<string> {
  return new Promise((resolve) => {
    const rl = createRL();
    const suffix = defaultValue ? ` ${C.dim}[${defaultValue}]${C.reset}` : "";
    rl.question(`  ${question}${suffix}: `, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultValue || "");
    });
  });
}

function choose(message: string, options: { key: string; label: string }[], defaultIdx = 0): Promise<string> {
  return new Promise((resolve) => {
    const rl = createRL();
    let output = `\n  ${message}\n\n`;
    options.forEach((opt, i) => {
      const marker = i === defaultIdx ? ` ${C.dim}(default)${C.reset}` : "";
      output += `    ${C.cyan}${i + 1}${C.reset}) ${opt.label}${marker}\n`;
    });
    output += `\n  Enter choice [${C.cyan}${defaultIdx + 1}${C.reset}]: `;
    rl.question(output, (answer) => {
      rl.close();
      const idx = parseInt(answer || String(defaultIdx + 1), 10) - 1;
      const selected = options[Math.max(0, Math.min(idx, options.length - 1))];
      resolve(selected.key);
    });
  });
}

// ─── Phase 1: Database ──────────────────────────────────────────────────────

function updateSchemaProvider(provider: string) {
  if (!fs.existsSync(SCHEMA_PATH)) return;
  let schema = fs.readFileSync(SCHEMA_PATH, "utf-8");
  // Only replace provider inside datasource db { ... } block, not generator client
  schema = schema.replace(
    /(datasource\s+db\s*\{[^}]*provider\s*=\s*)"[^"]*"/,
    `$1"${provider}"`,
  );
  fs.writeFileSync(SCHEMA_PATH, schema);
}

function generateSecrets() {
  return {
    encryptionKey: crypto.randomBytes(32).toString("hex"),
    csrfSecret: crypto.randomBytes(32).toString("hex"),
  };
}

function writeEnvFile(provider: string, databaseUrl: string, shopifyKey = "", shopifySecret = "") {
  const { encryptionKey, csrfSecret } = generateSecrets();

  const content = `# ShopForge Environment Variables
# Generated by npm run setup — edit as needed

# === Shopify App Credentials ===
SHOPIFY_API_KEY=${shopifyKey}
SHOPIFY_API_SECRET=${shopifySecret}

# === Database ===
# Provider: ${provider}
DATABASE_URL=${databaseUrl}

# === Security (auto-generated) ===
ENCRYPTION_KEY=${encryptionKey}
CSRF_SECRET=${csrfSecret}

# === Optional ===
APP_URL=http://localhost:3000
SHOPIFY_SCOPES=
SHOPIFY_BILLING_TEST=true
LOG_LEVEL=debug
RESEND_API_KEY=
RESEND_FROM_EMAIL=ShopForge <onboarding@resend.dev>
REDIS_URL=
CRON_SECRET=
`;

  fs.writeFileSync(ENV_PATH, content);
}

async function phaseDatabase(providerArg?: string): Promise<{ provider: string; url: string }> {
  log("Configuring database...");

  // Non-interactive: --provider flag
  if (providerArg) {
    const preset = PRESETS[providerArg];
    if (!preset) fail(`Unknown provider: ${providerArg}. Valid: ${Object.keys(PRESETS).join(", ")}`);
    updateSchemaProvider(providerArg);
    writeEnvFile(providerArg, preset.url);
    ok(`Database: ${providerArg}`);
    return { provider: providerArg, url: preset.url };
  }

  // Interactive: let user choose
  const options = Object.entries(PRESETS).map(([key, val]) => ({ key, label: val.label }));
  // Put sqlite first for default
  options.sort((a, b) => {
    if (a.key === "sqlite") return -1;
    if (b.key === "sqlite") return 1;
    return 0;
  });

  const choice = await choose("Choose your database:", options, 0);
  const preset = PRESETS[choice];

  // If PostgreSQL or MySQL, ask for custom URL
  let url = preset.url;
  if (choice !== "sqlite") {
    const customUrl = await ask(`Database URL (or press Enter for default)`, preset.url);
    url = customUrl;
  }

  updateSchemaProvider(choice);
  ok(`Database: ${choice}`);
  return { provider: choice, url };
}

// ─── Phase 2: Shopify App ───────────────────────────────────────────────────

async function phaseShopify(): Promise<{ key: string; secret: string }> {
  console.log("");
  log("Shopify App credentials");
  console.log(`  ${C.dim}───────────────────────────────────────${C.reset}`);

  // Check if already configured
  if (fs.existsSync(SHOPIFY_TOML)) {
    const toml = fs.readFileSync(SHOPIFY_TOML, "utf-8");
    const clientIdMatch = toml.match(/client_id\s*=\s*"([^"]+)"/);
    if (clientIdMatch && clientIdMatch[1] && !clientIdMatch[1].startsWith("your_")) {
      warn(`shopify.app.toml already has client_id: ${clientIdMatch[1].slice(0, 8)}...`);
      const skip = await ask("Skip Shopify setup? (y/n)", "y");
      if (skip.toLowerCase() === "y") {
        ok("Skipped — fill SHOPIFY_API_KEY and SHOPIFY_API_SECRET in .env later");
        return { key: "", secret: "" };
      }
    }
  }

  // Guide user
  console.log("");
  console.log(`  ${C.bold}Create a Shopify App:${C.reset}`);
  console.log(`  ${C.cyan}1.${C.reset} Go to ${C.bold}https://partners.shopify.com${C.reset}`);
  console.log(`  ${C.cyan}2.${C.reset} Apps → ${C.bold}Create app${C.reset} (name it anything, e.g. "ShopForge Dev")`);
  console.log(`  ${C.cyan}3.${C.reset} Configuration → API credentials → copy ${C.bold}API Key${C.reset} and ${C.bold}API Secret Key${C.reset}`);
  console.log(`  ${C.dim}   (You can also paste them later in .env)${C.reset}`);
  console.log("");

  const key = await ask("Paste API Key (or press Enter to skip)", "");
  const secret = key ? await ask("Paste API Secret Key") : "";

  if (key && secret) {
    ok(`Credentials received (API Key: ${key.slice(0, 8)}...)`);

    // Update shopify.app.toml client_id
    if (fs.existsSync(SHOPIFY_TOML)) {
      let toml = fs.readFileSync(SHOPIFY_TOML, "utf-8");
      toml = toml.replace(/client_id\s*=\s*"[^"]*"/, `client_id = "${key}"`);
      fs.writeFileSync(SHOPIFY_TOML, toml);
      ok("Updated shopify.app.toml client_id");
    }
  } else {
    warn("Skipped — you can fill in .env later");
  }

  return { key, secret };
}

// ─── Phase 3: Database init ─────────────────────────────────────────────────

function phaseDatabaseInit() {
  console.log("");
  log("Initializing database tables...");

  try {
    const result = spawnSync("npx", ["prisma", "db", "push", "--skip-generate"], {
      cwd: ROOT,
      stdio: "pipe",
      timeout: 30_000,
      shell: process.platform === "win32",
    });
    if (result.status !== 0) {
      const stderr = result.stderr?.toString().split("\n")[0] || "unknown error";
      throw new Error(stderr);
    }
    ok("Database tables created");
  } catch (err: any) {
    warn(`Database init failed: ${err.message?.split("\n")[0] || err}`);
    warn("You can run it manually: npm run db:push");
  }
}

// ─── Parse args ──────────────────────────────────────────────────────────────

function parseArgs() {
  const args = process.argv.slice(2);
  const result: { provider?: string; quick: boolean; dbOnly: boolean } = {
    quick: false,
    dbOnly: false,
  };

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case "--provider":
        result.provider = args[++i];
        break;
      case "--quick":
        result.quick = true;
        break;
      case "--db-only":
        result.dbOnly = true;
        break;
      default:
        fail(`Unknown argument: ${args[i]}`);
    }
  }
  return result;
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  const opts = parseArgs();

  banner("ShopForge Setup");

  // ── Guard: CI/Docker ──────────────────────────────────────────────────
  if (process.env.DATABASE_URL && process.env.CI) {
    ok("CI/Docker mode — skipping setup");
    return;
  }

  // ── Guard: .env already exists ────────────────────────────────────────
  if (fs.existsSync(ENV_PATH) && !opts.provider && !opts.quick) {
    const envContent = fs.readFileSync(ENV_PATH, "utf-8");
    const hasKey = /SHOPIFY_API_KEY=.+/.test(envContent) && !/SHOPIFY_API_KEY=your_/.test(envContent);
    if (hasKey) {
      ok(".env already configured");
      console.log(`    To reconfigure: delete .env and run ${C.cyan}npm run setup${C.reset}`);
      return;
    }
    warn(".env exists but Shopify credentials are missing — continuing setup");
  }

  // ── Phase 1: Database ─────────────────────────────────────────────────
  const db = await phaseDatabase(opts.provider);

  // ── Phase 2: Shopify (skip in quick/db-only mode) ─────────────────────
  let shopify = { key: "", secret: "" };
  if (!opts.dbOnly && !opts.provider) {
    if (opts.quick) {
      warn("Quick mode — skipping Shopify setup");
    } else {
      shopify = await phaseShopify();
    }
  }

  // ── Write .env (if not already written by --provider) ─────────────────
  if (!opts.provider) {
    // Read existing .env to preserve secrets if re-running
    let existingKey = shopify.key;
    let existingSecret = shopify.secret;

    if (fs.existsSync(ENV_PATH)) {
      const old = fs.readFileSync(ENV_PATH, "utf-8");
      const keyMatch = old.match(/SHOPIFY_API_KEY=(.+)/);
      const secretMatch = old.match(/SHOPIFY_API_SECRET=(.+)/);
      if (keyMatch?.[1] && !existingKey) existingKey = keyMatch[1].trim();
      if (secretMatch?.[1] && !existingSecret) existingSecret = secretMatch[1].trim();
    }

    writeEnvFile(db.provider, db.url, existingKey, existingSecret);
    ok(".env created");
  }

  // ── Phase 3: Database init (skip in CI/Docker) ────────────────────────
  if (!process.env.CI && !process.env.DOCKER_BUILD) {
    phaseDatabaseInit();
  }

  // ── Done ──────────────────────────────────────────────────────────────
  console.log("");
  console.log(`  ${C.bold}${C.green}✓ ShopForge is ready!${C.reset}`);
  console.log("");

  // Check if Shopify credentials are still missing
  const envContent = fs.readFileSync(ENV_PATH, "utf-8");
  const needsShopify = !/SHOPIFY_API_KEY=.+/.test(envContent) || /SHOPIFY_API_KEY=$/m.test(envContent);

  if (needsShopify) {
    console.log(`  ${C.yellow}Before running dev:${C.reset}`);
    console.log(`    Edit ${C.cyan}.env${C.reset} — fill in SHOPIFY_API_KEY and SHOPIFY_API_SECRET`);
    console.log(`    (Get them from https://partners.shopify.com)`);
    console.log("");
  }

  console.log(`  Start developing:`);
  console.log(`    ${C.cyan}npm run dev${C.reset}`);
  console.log("");
}

main().catch((err) => {
  console.error(`  ${C.red}Setup failed:${C.reset} ${err.message}`);
  process.exit(1);
});
