#!/usr/bin/env node
// @ts-nocheck — CommonJS setup script, not type-checked
/**
 * ShopForge Database Setup
 *
 * Responsibilities:
 *   1. CI / Docker (DATABASE_URL injected) → no-op, preserve existing schema
 *   2. --provider <name> → update schema provider + generate .env secrets
 *   3. Interactive prompt (TTY) → full guided setup
 *   4. No TTY + no config → print instructions and exit 1
 *
 * IMPORTANT: This script NEVER runs `prisma db push` — that is a developer
 * action, not an install-time action.  It also never overwrites an existing
 * .env file.
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");

const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.join(ROOT, ".env");
const SCHEMA_PATH = path.join(ROOT, "prisma", "schema.prisma");

// ─── Database presets ────────────────────────────────────────────────────────

const PRESETS = {
  postgresql: {
    label: "PostgreSQL (recommended for production)",
    url: "postgresql://user:password@localhost:5432/shopforge",
  },
  mysql: {
    label: "MySQL",
    url: "mysql://user:password@localhost:3306/shopforge",
  },
  sqlite: {
    label: "SQLite (zero config, great for development)",
    url: "file:./dev.db",
  },
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function log(msg) {
  console.log(`\n  \x1b[36m●\x1b[0m ${msg}`);
}

function success(msg) {
  console.log(`  \x1b[32m✓\x1b[0m ${msg}`);
}

function fail(msg) {
  console.error(`  \x1b[31m✗\x1b[0m ${msg}`);
  process.exit(1);
}

/**
 * Prompt user to select from numbered options.
 */
function promptChoice(message, options) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const keys = Object.keys(options);
    let output = `\n  ${message}\n\n`;
    keys.forEach((key, i) => {
      const suffix = key === "postgresql" ? " \x1b[90m← recommended\x1b[0m" : "";
      output += `    \x1b[36m${i + 1}\x1b[0m) ${options[key]}${suffix}\n`;
    });
    output += `\n  Enter choice [\x1b[36m1\x1b[0m]: `;
    rl.question(output, (answer) => {
      rl.close();
      const idx = parseInt(answer || "1", 10) - 1;
      const selected = keys[Math.max(0, Math.min(idx, keys.length - 1))];
      resolve(selected);
    });
  });
}

/**
 * Generate .env with database URL and fresh security secrets.
 * Never overwrites an existing .env.
 */
function generateEnv(provider, databaseUrl) {
  const encryptionKey = require("crypto").randomBytes(32).toString("hex");
  const csrfSecret = require("crypto").randomBytes(32).toString("hex");

  const content = `# ShopForge Environment Variables
# Generated by setup-db.js — edit as needed

# === Shopify App Credentials (from Partner Dashboard) ===
SHOPIFY_API_KEY=
SHOPIFY_API_SECRET=

# === Database ===
# Provider: ${provider}
DATABASE_URL=${databaseUrl}

# === Security ===
# AES-256-GCM key for token encryption (auto-generated)
ENCRYPTION_KEY=${encryptionKey}
CSRF_SECRET=${csrfSecret}

# === Optional ===
APP_URL=http://localhost:3000
SHOPIFY_SCOPES=
SHOPIFY_BILLING_TEST=true
LOG_LEVEL=debug
RESEND_API_KEY=
RESEND_FROM_EMAIL=ShopForge <onboarding@resend.dev>
REDIS_URL=
CRON_SECRET=
`;

  fs.writeFileSync(ENV_PATH, content);
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  console.log("");
  console.log("  \x1b[1m━━━ ShopForge Database Setup ━━━\x1b[0m");

  // ── 1. Parse CLI arguments ──────────────────────────────────────────────
  const args = process.argv.slice(2);
  let providerArg = null;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--provider") {
      providerArg = args[++i];
      if (!providerArg || !PRESETS[providerArg]) {
        fail(`Unknown provider: ${providerArg || "(missing)"}. Valid: ${Object.keys(PRESETS).join(", ")}`);
      }
    } else {
      fail(`Unknown argument: ${args[i]}`);
    }
  }

  // ── 2. Conflict: --provider + DATABASE_URL ─────────────────────────────
  if (providerArg && process.env.DATABASE_URL) {
    fail("Cannot use --provider when DATABASE_URL is already set. Remove one or the other.");
  }

  // ── 3. CI / Docker: DATABASE_URL injected — nothing to do ──────────────
  if (process.env.DATABASE_URL) {
    success("DATABASE_URL detected — skipping setup (CI/Docker mode).");
    return;
  }

  // ── 4. --provider: update schema + generate .env ───────────────────────
  if (providerArg) {
    // Update provider in existing schema (preserves custom models)
    if (fs.existsSync(SCHEMA_PATH)) {
      let schema = fs.readFileSync(SCHEMA_PATH, "utf-8");
      schema = schema.replace(
        /provider\s*=\s*"[^"]*"/,
        `provider = "${providerArg}"`,
      );
      fs.writeFileSync(SCHEMA_PATH, schema);
    }

    // Generate .env with secrets
    generateEnv(providerArg, PRESETS[providerArg].url);
    success(`Database configured: ${providerArg}`);
    success("Secrets generated (ENCRYPTION_KEY, CSRF_SECRET)");
    return;
  }

  // ── 5. .env already exists — skip ──────────────────────────────────────
  if (fs.existsSync(ENV_PATH)) {
    success(".env already configured — skipping.");
    console.log("    To reconfigure: delete .env and run \x1b[36mnpm run setup\x1b[0m");
    return;
  }

  // ── 6. Non-interactive / production — cannot prompt ────────────────────
  const isCI = process.env.CI || process.env.DOCKER_BUILD || process.env.NODE_ENV === "production";
  if (isCI || !process.stdin.isTTY) {
    fail("No DATABASE_URL configured and terminal is not interactive. Set DATABASE_URL or run `npm run setup` in a terminal.");
  }

  // ── 7. Interactive prompt ──────────────────────────────────────────────
  const choiceMap = {};
  Object.keys(PRESETS).forEach((key) => {
    choiceMap[key] = PRESETS[key].label;
  });

  const choice = await promptChoice("Choose your database:", choiceMap);
  const preset = PRESETS[choice];

  log(`Configuring ${choice}...`);

  generateEnv(choice, preset.url);
  success(".env created");

  console.log("");
  console.log("  \x1b[1m\x1b[32m✓ ShopForge is ready!\x1b[0m");
  console.log("");
  console.log("  Next steps:");
  console.log("    1. Edit \x1b[36m.env\x1b[0m — fill in SHOPIFY_API_KEY and SHOPIFY_API_SECRET");
  console.log("    2. Run  \x1b[36mnpm run db:push\x1b[0m — sync schema to database");
  console.log("    3. Run  \x1b[36mnpm run dev\x1b[0m — start the dev server");
  console.log("");
}

main().catch((err) => {
  console.error("  Setup failed:", err.message);
  process.exit(1);
});
