#!/usr/bin/env node
// @ts-nocheck — CommonJS setup script, not type-checked
/**
 * ShopForge Database Setup
 *
 * Runs automatically on first `npm install` (via postinstall) or manually
 * via `npm run setup`. Detects existing .env and skips to avoid overwriting.
 *
 * Flow:
 *   1. .env exists → skip (already configured)
 *   2. CI/Docker detected → auto-configure SQLite
 *   3. TTY available → interactive prompt (PostgreSQL / MySQL / SQLite)
 *   4. No TTY → print instructions and exit
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");
const { execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.join(ROOT, ".env");
const SCHEMA_PATH = path.join(ROOT, "prisma", "schema.prisma");
const TEMPLATE_PATH = path.join(ROOT, "prisma", "schema.prisma.template");

// ─── Database presets ────────────────────────────────────────────────────────

const PRESETS = {
  postgresql: {
    label: "PostgreSQL (recommended for production)",
    url: "postgresql://user:password@localhost:5432/shopforge",
  },
  mysql: {
    label: "MySQL",
    url: "mysql://user:password@localhost:3306/shopforge",
  },
  sqlite: {
    label: "SQLite (zero config, great for development)",
    url: "file:./dev.db",
  },
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function log(msg) {
  console.log(`\n  \x1b[36m●\x1b[0m ${msg}`);
}

function success(msg) {
  console.log(`  \x1b[32m✓\x1b[0m ${msg}`);
}

function warn(msg) {
  console.log(`  \x1b[33m⚠\x1b[0m ${msg}`);
}

/**
 * Prompt user to select from numbered options.
 * Returns the key of the selected option.
 */
function promptChoice(message, options) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    const keys = Object.keys(options);
    let output = `\n  ${message}\n\n`;
    keys.forEach((key, i) => {
      const suffix = key === "postgresql" ? " \x1b[90m← recommended\x1b[0m" : "";
      output += `    \x1b[36m${i + 1}\x1b[0m) ${options[key]}${suffix}\n`;
    });
    output += `\n  Enter choice [\x1b[36m1\x1b[0m]: `;

    rl.question(output, (answer) => {
      rl.close();
      const idx = parseInt(answer || "1", 10) - 1;
      const selected = keys[Math.max(0, Math.min(idx, keys.length - 1))];
      resolve(selected);
    });
  });
}

/**
 * Generate schema.prisma from template with the chosen provider.
 */
function generateSchema(provider) {
  const template = fs.readFileSync(TEMPLATE_PATH, "utf-8");
  const schema = template.replace(/__PROVIDER__/g, provider);
  fs.writeFileSync(SCHEMA_PATH, schema);
}

/**
 * Generate .env file with the chosen database URL and placeholder secrets.
 */
function generateEnv(provider, databaseUrl) {
  const encryptionKey = require("crypto").randomBytes(32).toString("hex");

  const content = `# ShopForge Environment Variables
# Generated by setup-db.js — edit as needed

# === Shopify App Credentials (from Partner Dashboard) ===
SHOPIFY_API_KEY=
SHOPIFY_API_SECRET=

# === Database ===
# Provider: ${provider}
DATABASE_URL=${databaseUrl}

# === Security ===
# AES-256-GCM key for token encryption (auto-generated)
ENCRYPTION_KEY=${encryptionKey}

# === Optional ===
APP_URL=http://localhost:3000
SHOPIFY_SCOPES=
SHOPIFY_BILLING_TEST=true
LOG_LEVEL=debug
RESEND_API_KEY=
RESEND_FROM_EMAIL=ShopForge <onboarding@resend.dev>
REDIS_URL=
CRON_SECRET=
CSRF_SECRET=
`;

  fs.writeFileSync(ENV_PATH, content);
}

/**
 * Run prisma generate + prisma db push.
 */
function runPrismaSetup() {
  const opts = { cwd: ROOT, stdio: "inherit" };
  try {
    execFileSync("npx", ["prisma", "generate"], opts);
    execFileSync("npx", ["prisma", "db", "push", "--skip-generate"], opts);
  } catch (e) {
    warn("Prisma setup had issues — you can run manually:");
    console.log("    npx prisma generate");
    console.log("    npx prisma db push");
  }
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  console.log("");
  console.log("  \x1b[1m━━━ ShopForge Database Setup ━━━\x1b[0m");

  // 1. Skip if .env already exists
  if (fs.existsSync(ENV_PATH)) {
    success(".env already configured — skipping.");
    console.log("    To reconfigure: delete .env and run \x1b[36mnpm run setup\x1b[0m");
    return;
  }

  // 2. Auto-configure in CI / Docker
  const isCI = process.env.CI || process.env.DOCKER_BUILD || process.env.NODE_ENV === "production";
  if (isCI) {
    log("CI/Docker detected — auto-configuring SQLite...");
    generateSchema("sqlite");
    generateEnv("sqlite", PRESETS.sqlite.url);
    success("SQLite configured (file:./dev.db)");
    runPrismaSetup();
    return;
  }

  // 3. Interactive prompt (TTY required)
  if (!process.stdin.isTTY) {
    warn("Non-interactive terminal detected.");
    console.log("    Run \x1b[36mnpm run setup\x1b[0m in a terminal to configure your database.");
    console.log("    Or copy \x1b[36m.env.example\x1b[0m to .env and edit manually.");
    return;
  }

  // 4. Prompt user
  const choiceMap = {};
  Object.keys(PRESETS).forEach((key) => {
    choiceMap[key] = PRESETS[key].label;
  });

  const choice = await promptChoice("Choose your database:", choiceMap);
  const preset = PRESETS[choice];

  log(`Configuring ${choice}...`);

  // Generate schema from template
  generateSchema(choice);
  success("prisma/schema.prisma generated");

  // Generate .env
  generateEnv(choice, preset.url);
  success(".env created");

  // Run Prisma setup
  log("Initializing database...");
  runPrismaSetup();

  // Done
  console.log("");
  console.log("  \x1b[1m\x1b[32m✓ ShopForge is ready!\x1b[0m");
  console.log("");
  console.log("  Next steps:");
  console.log("    1. Edit \x1b[36m.env\x1b[0m — fill in SHOPIFY_API_KEY and SHOPIFY_API_SECRET");
  console.log("    2. Run  \x1b[36mnpm run dev\x1b[0m — start the dev server");
  console.log("");

  if (choice === "sqlite") {
    console.log("  \x1b[90mSQLite is great for development. For production, switch to PostgreSQL:\x1b[0m");
    console.log("  \x1b[90m  npm run setup   (after deleting .env)\x1b[0m");
    console.log("");
  }
}

main().catch((err) => {
  console.error("  Setup failed:", err.message);
  console.log("    Manual setup: copy .env.example → .env, then run: npx prisma generate && npx prisma db push");
  process.exit(1);
});
